# Generated by Django 5.2 on 2025-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_text_quote_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
